env:
  global:
    - PREFIX="/tmp/usr"

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra" CONFIGURE="--target=i686-linux-gnu"
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra" CONFIGURE="--target=i686-linux-gnu"
    - os: osx
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
      osx_image: xcode7.3
  allow_failures:
    - os: osx

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ArchC"
    on_success: change
    on_failure: always
    on_start: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ce13c79f5cdcf0e6788e
    on_success: change
    on_failure: always
    on_start: false

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CONFIGURE" == "--target=i686-linux-gnu" ] ; then sudo apt-get install -y gcc-multilib g++-multilib; fi
  - uname -a
  - env
  - export PATH="${PREFIX}/bin:${PATH}"
  - export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH}"
  - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - git clone --depth 1 https://github.com/ArchC/SystemC.git /tmp/SystemC
  - pushd /tmp/SystemC ; autoreconf -vif ; ./configure --prefix=${PREFIX}; make install -j3 ; popd
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git clone --depth 1 git://git.fedorahosted.org/git/elfutils.git /tmp/elfutils; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pushd /tmp/elfutils ; autoreconf -vif ; ./configure --prefix=${PREFIX} --enable-maintainer-mode; make install -j3 ; popd; fi

install:
  - autoreconf -vif
  - ./configure --prefix=$PREFIX $CONFIGURE
  - make -j3

before_script:


script:
  - make check
  - make install
  - pkg-config archc

after_success:


after_failure:


after_script:


before_deployment:


deployment:


after_deployment:
