# ArchC Configuration File 
# This file is automatically generated by the ArchC Installation script

#---------------------------------------------------------------------------
# Paths
#---------------------------------------------------------------------------
BINUTILS_PATH = binutils_path()
GDB_PATH = gdb_path()
CC = compiler()

#---------------------------------------------------------------------------
# Compiler Flags
#---------------------------------------------------------------------------
OPT = -O3
DEBUG = -g
OTHER = -Wno-deprecated
