# ArchC Configuration File 
# This file is automatically generated by the ArchC Installation script

#---------------------------------------------------------------------------
# Paths
#---------------------------------------------------------------------------
SYSTEMC_PATH = systemc_path()
TLM_PATH = tlm_path()
BINUTILS_PATH = binutils_path()
GDB_PATH = gdb_path()
CC = compiler()

#---------------------------------------------------------------------------
# Compiler Flags
#---------------------------------------------------------------------------
OPT = -O3
DEBUG = -g
OTHER = -Wno-deprecated

#---------------------------------------------------------------------------
# Simulator Flags
#---------------------------------------------------------------------------
TARGET_ARCH = systemc_target()
