/* ex: set tabstop=2 expandtab: 
   -*- Mode: C; tab-width: 2; indent-tabs-mode nil -*-
*/
/**
 * @file      relocation.h
 * @author    Bruno Cardoso Lopes (UNICAMP)
 * 
 * @author    The ArchC Team
 *            http://www.archc.org/
 *
 *            Computer Systems Laboratory (LSC)
 *            IC-UNICAMP
 *            http://www.lsc.ic.unicamp.br/
 *
 * @version   1.0
 * @date      Thu, 3 Jan 2012 20:05:00 -0300 
 * 
 * @brief     BFD library related code
 * 
 * @attention Copyright (C) 2002-2012 --- The ArchC Team
 *
 */

#ifndef _RELOCATION_H_
#define _RELOCATION_H_

/*  Relocations generated by ArchC should start at a very high
 *  enumeration boundary. This *must* happen because it allows
 *  existing bfd relocations to be used in case we want to link
 *  with object files generated from other binutils. */
#define AC_GENERIC_RELOCNUM_BEGIN   80
#define AC_USER_RELOCNUM_BEGIN   100

#endif /* _BFD_H_ */

/* @} */
